{{- if .Values.php_fpm.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-configs
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  {{- range .Values.php_fpm.configs.content }}
  {{ .name }}: |
  {{- .data | nindent 4 }}
  {{- end }}
{{- end }}
