{{- if .Values.php_fpm.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-php-envs
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.php_fpm.env | nindent 2 }}
{{- end }}
